language: php
dist: xenial
os: linux
php:
  - 7.4
  - 8.0
  - nightly

script:
  - composer update --prefer-lowest
  - composer phpcs
  - composer phpstan

cache:
  directories:
  - $HOME/.cache/composer/files
